ALTER TABLE recipes ADD COLUMN nutrition_kcal DOUBLE PRECISION;
ALTER TABLE recipes ADD COLUMN nutrition_fat DOUBLE PRECISION;
ALTER TABLE recipes ADD COLUMN nutrition_protein DOUBLE PRECISION;
ALTER TABLE recipes ADD COLUMN nutrition_carbs DOUBLE PRECISION;
ALTER TABLE recipes ADD COLUMN nutrition_fiber DOUBLE PRECISION;
